#!/usr/bin/env node
const align = require('align-yaml');
const fs = require('fs');
const commandLineArgs = require('command-line-args');

const optionDefinitions = [
    { name: 'file', alias: 'f', type: String },
];

const options = commandLineArgs(optionDefinitions);

function normalize(file) {
  if (!file) {
    console.error("file is required");
    return;
  }
  const str = fs.readFileSync(file, 'utf8');
  console.log(align(str));
} 

normalize(options.file);
