#!/bin/bash

secrets_array=$(ls ../pack/secrets)

source ./lib/yaml

create_secrets() {
  for i in "${secrets_array[@]}"
  do
    file=../pack/secrets/$i
    filename=$(basename -- "$file")
    secret_name=${filename%%.*}
    secret_value=$(cat $file)
    docker secret rm $secret_name >&-
    echo $secret_value | docker secret create $secret_name - >&-
  done
}
