#!/bin/bash

stack_name=

while [ "$1" != "" ]; do
    case $1 in
        -s | --stack )  shift
                        stack_name=$1
                        ;;
    esac
    shift
done

source ./lib/yaml
source ./lib/mo

current_path=$(pwd)

# echo 
cd ../pack

create_variables packfile.yml
echo "Swarmpack: Packaging $pack_name $pack_version"

create_variables values.yml

cat docker-compose.tpl.yml | mo > docker-compose-tmp.yml

$current_path/lib/normalizeYml -f docker-compose-tmp.yml > docker-compose.yml

rm docker-compose-tmp.yml

echo "Swarmpack: Deploying $pack_name $pack_version"
docker-compose push

docker stack deploy --compose-file docker-compose.yml $stack_name

rm docker-compose.yml


